name: widget-server pipe
on:
  push:
    branches: [ feat/github-workflows ]

# [x] - aws configure - credential config
# [x] - aws ecr - ecr login
# [ ] - image build
# [ ] - image tag
# [ ] - image push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push image to AWS ECR
        id: build-push-image
        env:
          ECR_REGISTER: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
          IMAGE_TAG: ${{steps.generate-tag.outputs.sha}}

        run: |
          docker build -t $ECR_REGISTER/ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTER/ECR_REPOSITORY:$IMAGE_TAG





